import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'HackIllinois Leaderboard website',
  description: 'Generated by create next app to build a leaderboard of interview',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      {/* This is to help with extensions blocking getting API */}
      <body className={'${inter.className} bg-slate-800 text-slate-100 container mx-auto p-4'}>{children}</body>
    </html>
  )
}
